game:
  standard-mode:
    name: standard
  survival-mode:
    name: survival

JDBC_DRIVER_CLASS_NAME: org.postgresql.Driver

spring:
  datasource:
    jdbc-url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: ${JDBC_DRIVER_CLASS_NAME}
  flyway:
    url: ${JDBC_URL}
    user: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    baseline-on-migrate: true