server:
  port: 8082

spring:
  datasource:
    jdbc-url: jdbc:mariadb://127.0.0.1:3306/typewars_records
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    url: jdbc:mariadb://127.0.0.1:3306/typewars_records
    user: root
    password: root
    baseline-on-migrate: true